# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tes.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gambar = QtWidgets.QLabel(self.centralwidget)
        self.gambar.setGeometry(QtCore.QRect(30, 100, 300, 300))
        self.gambar.setText("")
        self.gambar.setObjectName("gambar")
        self.tombolLoad = QtWidgets.QPushButton(self.centralwidget)
        self.tombolLoad.setGeometry(QtCore.QRect(30, 510, 145, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.tombolLoad.setFont(font)
        self.tombolLoad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tombolLoad.setObjectName("tombolLoad")
        self.tombolFind = QtWidgets.QPushButton(self.centralwidget)
        self.tombolFind.setGeometry(QtCore.QRect(180, 510, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.tombolFind.setFont(font)
        self.tombolFind.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tombolFind.setObjectName("tombolFind")
        self.tombolEuc = QtWidgets.QRadioButton(self.centralwidget)
        self.tombolEuc.setGeometry(QtCore.QRect(30, 410, 300, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.tombolEuc.setFont(font)
        self.tombolEuc.setObjectName("tombolEuc")
        self.tombolCosi = QtWidgets.QRadioButton(self.centralwidget)
        self.tombolCosi.setGeometry(QtCore.QRect(30, 440, 300, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.tombolCosi.setFont(font)
        self.tombolCosi.setObjectName("tombolCosi")
        self.query = QtWidgets.QLabel(self.centralwidget)
        self.query.setGeometry(QtCore.QRect(30, 60, 150, 38))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.query.setFont(font)
        self.query.setObjectName("query")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(30, 470, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.tombolNext = QtWidgets.QPushButton(self.centralwidget)
        self.tombolNext.setGeometry(QtCore.QRect(570, 480, 70, 70))
        self.tombolNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tombolNext.setText("")
        self.tombolNext.setObjectName("tombolNext")
        self.gambar2 = QtWidgets.QLabel(self.centralwidget)
        self.gambar2.setGeometry(QtCore.QRect(370, 100, 300, 300))
        self.gambar2.setText("")
        self.gambar2.setObjectName("gambar2")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(370, 60, 150, 38))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.judul = QtWidgets.QLabel(self.centralwidget)
        self.judul.setGeometry(QtCore.QRect(190, 10, 350, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        self.judul.setFont(font)
        self.judul.setObjectName("judul")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 465, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tombolPrev = QtWidgets.QPushButton(self.centralwidget)
        self.tombolPrev.setGeometry(QtCore.QRect(410, 480, 70, 70))
        self.tombolPrev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tombolPrev.setText("")
        self.tombolPrev.setObjectName("tombolPrev")
        self.similarity = QtWidgets.QLabel(self.centralwidget)
        self.similarity.setGeometry(QtCore.QRect(380, 410, 250, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.similarity.setFont(font)
        self.similarity.setText("")
        self.similarity.setObjectName("similarity")
        self.similarity2 = QtWidgets.QLabel(self.centralwidget)
        self.similarity2.setGeometry(QtCore.QRect(600, 410, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.similarity2.setFont(font)
        self.similarity2.setText("")
        self.similarity2.setObjectName("similarity2")
        self.home = QtWidgets.QPushButton(self.centralwidget)
        self.home.setGeometry(QtCore.QRect(0, 0, 700, 575))
        self.home.setText("")
        self.home.setObjectName("home")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ternyata Kelar :)"))
        self.tombolLoad.setText(_translate("MainWindow", "Load"))
        self.tombolFind.setText(_translate("MainWindow", "Find"))
        self.tombolEuc.setText(_translate("MainWindow", "Euclidian Distance"))
        self.tombolCosi.setText(_translate("MainWindow", "Cosine Similarity"))
        self.query.setText(_translate("MainWindow", "Query"))
        self.result.setText(_translate("MainWindow", "Result"))
        self.judul.setText(_translate("MainWindow", "FACE RECOGNITION"))
        self.label.setText(_translate("MainWindow", "Image(s)"))
